name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip python3-setuptools libltdl-dev libssl-dev autoconf automake libtool pkg-config
          pip install --upgrade cython buildozer

          # Установка Android SDK Command-Line Tools
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O android-tools.zip
          unzip android-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/tools

          # Принятие лицензий и установка необходимых компонентов Android SDK
          yes | $ANDROID_HOME/cmdline-tools/tools/bin/sdkmanager --licenses
          yes | $ANDROID_HOME/cmdline-tools/tools/bin/sdkmanager --install "build-tools;34.0.0" "platforms;android-34" "platform-tools"

          # Проверка наличия Aidl
          ls $ANDROID_HOME/build-tools/34.0.0/aidl || echo "Aidl not found!"

      - name: Build APK
        run: |
          export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/build-tools/34.0.0
          buildozer init
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
